# Generated by Django 3.2 on 2022-04-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_class', models.CharField(max_length=1, verbose_name='Recipe|class')),
                ('name', models.CharField(max_length=50, verbose_name='Recipe|name')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='Recipe|summary')),
                ('requirements', models.TextField(blank=True, verbose_name='Recipe|requirements')),
                ('steps', models.TextField(blank=True, verbose_name='Recipe|steps')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipies',
                'ordering': ['recipe_class'],
            },
        ),
    ]
